### ISSUE TITLE
NFD Feature Rules for GPU type aren't deployed

### ISSUE THREAD

**Issue by brgavino** [intel/intel-technology-enabling-for-openshift#193]
Per https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/cmd/gpu_plugin/labels.md , 

Nodes can label the cards that are available using these rules: https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/deployments/nfd/overlays/node-feature-rules/platform-labeling-rules.yaml

This should probably be installed by default since this is via the OpenShift Operator deployment; otherwise admins have to create the rules themselves.

**Comment by brgavino** [comment]
Here's a version that works, without the "extendedResources" tag

[platform-labeling-rules.yaml.txt](https://github.com/intel/intel-technology-enabling-for-openshift/files/14044962/platform-labeling-rules.yaml.txt)

**Comment by uMartinXu** [comment]
@brgavino  Thanks for your suggestion. :-)

To align with RH OpenShift AI [Dashboard Accelerator Profile](https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science_self-managed/2.4/html/working_on_data_science_projects/working-with-accelerators_accelerators#overview-of-accelerators_accelerators), the taints/tolerance mechanism will be used by us to support the Heterogenous(different type of) Intel dGPU product. 

We are working on a related solution for the user.

And as cluster administrators, they can also pick the other way like the labelling you mentioned and use them with the nodeselect.

**Comment by uMartinXu** [comment]
duplcated with https://github.com/intel/intel-technology-enabling-for-openshift/issues/216
