### ISSUE TITLE
Support SHA Digests image in the device plugin CRD

### ISSUE THREAD

**Issue by uMartinXu** [intel/intel-technology-enabling-for-openshift#26]
## Summary
The SHA Digests should be supported by Intel device plugin operator and protect the integrity of the device plugin image.
## Detail
By default, on OCP, the SHA256 Digests is used to point to the device plugin image and secure the integration of the image.   
While intel device plugin operator can't support the SHA26 Digests.
See [#03220971](https://access.redhat.com/support/cases/#/case/03220971)
see [Image SHA Digests vs. Image Tags](https://access.redhat.com/articles/4975041)

## Suggestion Solutions
- to work around this issue, while creating the DevicePlugin CR (using SGXDevicePluin as an example), an errormessage like "intel-sgx-plugin@sha256. Make sure you use '/intel-sgx-plugin:<version>'"might be shown to suggest users replace the SHA digests with the image tag like 0.24.0. 
- to resolve the issue, the intel device plugin device plugin operator should support SHA Digests in the device plugin CRD

**Comment by uMartinXu** [comment]
@mythi actually the tags are still allowed, it just can't be the default configuration shipped with the operator bundle. This means if the user wants to use the tag, the tag image URL has to be manually input by user. See the first item of Suggestion Solutions.

**Comment by uMartinXu** [comment]
I think the problem is we need to figure out the seamless upgrade behavior when the user uses the SHA digests. 
- Should we let the new operator upgrade the deviceplugin images with the new SHA digests shipped together with the new operator bundle or
- With SHA digests without user's involvement the new deviceplugin images will not be upgraded

**Comment by mythi** [comment]
> I think the problem is we need to figure out the seamless upgrade behavior when the user uses the SHA digests.

This is the question we have hoped to get Redhat's feedback for quite some time. Do we have anything yet?

**Comment by uMartinXu** [comment]
According to the feedback from RH from https://access.redhat.com/support/cases/#/case/03220971

"Should we let the new operator upgrade the deviceplugin images with the new SHA digests shipped together with the new operator bundle?"

- Basically that should just be owned by the operator developer? OLM itself just isn't part of this process.

**Comment by mythi** [comment]
Fixed in v0.26.1 release

**Comment by hershpa** [comment]
Are we ready to close this issue?
