### ISSUE TITLE
Device Plugin CR webhook error

### ISSUE THREAD

**Issue by hershpa** [intel/intel-technology-enabling-for-openshift#29]
### Summary:
When creating a `[Sgx/Qat/Gpu]DevicePlugin` CR after the Intel Device Plugins operator is installed, a webhook error is observed. This error is observed via OpenShift web console as well as through CLI. 

### Error message:
`Error "failed calling webhook "vsgxdeviceplugin.kb.io": failed to call webhook: Post "https://inteldeviceplugins-controller-manager-service.openshift-operators.svc:443/validate-deviceplugin-intel-com-v1-sgxdeviceplugin?timeout=10s": dial tcp 10.131.1.204:9443: connect: connection refused" for field "undefined".`

### Analysis:
A webhook is called to validate `[Sgx/Qat/Gpu]DevicePlugin` CR yaml input parameters when user creates the DevicePlugin. Initial evidence suggests this issue is network or environment related. 

### Impact:
User is unable to consistently create `[Sgx/Qat/Gpu]DevicePlugin` CR on OpenShift cluster. User experience impacted. The error is not consistent, on the first try, the error may appear and then continue to appear for subsequent retries. If the user keeps clicking the "Create" button on web console, the DevicePlugin CR is eventually created without error.

**Comment by hershpa** [comment]
Hi @mythi, any thoughts on this issue? Have you seen this before? Thanks in advance.

**Comment by mythi** [comment]
> Initial evidence suggests this issue is network or environment related.

Can you think of what has changed since it worked? I know webhook errors can occur if https gets routed through a proxy but this looks different.

**Comment by mythi** [comment]
Is there a way to reproduce this? Something we have improved recently is that the operator now uses readiness probes, also for the webhooks. Could it be this error triggers if the webhook is not yet up properly?

**Comment by hershpa** [comment]
It is reproducible. The operator bundle and container images are based on `v0.26.0`. Anything particular we can check to ensure webhook is setup and running properly? I can see in the logs that the webhook is registered successfully, started the webhook server and the health probe running. We are creating the DevicePlugin CR and noticing the webhook error after all this setup happens in the below log.

```
GET:https://172.30.0.1:443/apis/ingress.operator.openshift.io/v1?timeout=32s
I0417 20:28:01.641213       1 listener.go:44] "controller-runtime/metrics: Metrics server is starting to listen" addr="127.0.0.1:8080"
I0417 20:28:01.641757       1 webhook.go:124] "controller-runtime/builder: Registering a mutating webhook" GVK="deviceplugin.intel.com/v1, Kind=SgxDevicePlugin" path="/mutate-deviceplugin-intel-com-v1-sgxdeviceplugin"
I0417 20:28:01.641811       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/mutate-deviceplugin-intel-com-v1-sgxdeviceplugin"
I0417 20:28:01.641856       1 webhook.go:153] "controller-runtime/builder: Registering a validating webhook" GVK="deviceplugin.intel.com/v1, Kind=SgxDevicePlugin" path="/validate-deviceplugin-intel-com-v1-sgxdeviceplugin"
I0417 20:28:01.641879       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/validate-deviceplugin-intel-com-v1-sgxdeviceplugin"
I0417 20:28:01.641955       1 webhook.go:124] "controller-runtime/builder: Registering a mutating webhook" GVK="deviceplugin.intel.com/v1, Kind=GpuDevicePlugin" path="/mutate-deviceplugin-intel-com-v1-gpudeviceplugin"
I0417 20:28:01.641980       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/mutate-deviceplugin-intel-com-v1-gpudeviceplugin"
I0417 20:28:01.642001       1 webhook.go:153] "controller-runtime/builder: Registering a validating webhook" GVK="deviceplugin.intel.com/v1, Kind=GpuDevicePlugin" path="/validate-deviceplugin-intel-com-v1-gpudeviceplugin"
I0417 20:28:01.642018       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/validate-deviceplugin-intel-com-v1-gpudeviceplugin"
I0417 20:28:01.642066       1 webhook.go:124] "controller-runtime/builder: Registering a mutating webhook" GVK="deviceplugin.intel.com/v1, Kind=QatDevicePlugin" path="/mutate-deviceplugin-intel-com-v1-qatdeviceplugin"
I0417 20:28:01.642084       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/mutate-deviceplugin-intel-com-v1-qatdeviceplugin"
I0417 20:28:01.642105       1 webhook.go:153] "controller-runtime/builder: Registering a validating webhook" GVK="deviceplugin.intel.com/v1, Kind=QatDevicePlugin" path="/validate-deviceplugin-intel-com-v1-qatdeviceplugin"
I0417 20:28:01.642123       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/validate-deviceplugin-intel-com-v1-qatdeviceplugin"
I0417 20:28:01.642169       1 server.go:149] "controller-runtime/webhook: Registering webhook" path="/pods-sgx"
I0417 20:28:01.642192       1 main.go:207] "setup: starting manager"
I0417 20:28:01.642654       1 server.go:217] "controller-runtime/webhook/webhooks: Starting webhook server"
I0417 20:28:01.642760       1 internal.go:369] "intel-device-plugins-manager: Starting server" path="/metrics" kind="metrics" addr="127.0.0.1:8080"
I0417 20:28:01.643160       1 certwatcher.go:131] "controller-runtime/certwatcher: Updated current TLS certificate"
I0417 20:28:01.643247       1 server.go:271] "controller-runtime/webhook: Serving webhook server" host="" port=9443
I0417 20:28:01.643831       1 internal.go:369] "intel-device-plugins-manager: Starting server" kind="health probe" addr="[::]:8081"
```

**Comment by vbedida79** [comment]
Also noticed, the controller manager pod has few restarts, could that be something related? Didn't find any errors in logs, as it restarts.
`inteldeviceplugins-controller-manager-7d8b6cd565-fdm2g            2/2     Running     4 (11m ago)   78m`

**Comment by mythi** [comment]
can you try increasing the pod cpu/mem resources if that helps?

**Comment by hershpa** [comment]
This issue was not observed on another OpenShift cluster. Low priority and not a gating item.
