### ISSUE TITLE
Facing issues when trying to build DGPU driver image via KMM on OKD ie. Openshift upstream

### ISSUE THREAD

**Issue by fayazahamedj** [intel/intel-technology-enabling-for-openshift#45]
Hello Team, 

We are working on the On-premise Build Mode approach via KMM to build DGPU driver image documented in below github link as we are using a 6.x kernel version with OKD. 

[https://github.com/intel/intel-technology-enabling-for-openshift/tree/main/kmmo#managing-intel-dgpu-driver-with-kmm-operator]

using On-premise Build Mode
Prior to using this mode, run the following commands to create a ConfigMap and include the dockerfile to build the driver container image:

```
$ git clone https://github.com/intel/intel-data-center-gpu-driver-for-openshift.git && cd intel-data-center-GPU-driver-for-openshift/docker

$oc create -n openshift-kmm configmap intel-dgpu-dockerfile-configmap --from-file=dockerfile=intel-dgpu-driver.Dockerfile

To use this mode, run the following command:

$ oc apply -f https://github.com/intel/intel-technology-enabling-for-openshift/blob/main/kmmo/intel-dgpu-on-premise-build-mode.yaml
```

Herein we have slight changes made in the configmap as driver toolkit is not available for OKD & we have build a custom image.  Build is getting triggered & we are seeing below error(snippet below) 

Also sharing the complete logs of the build pod for the analysis, require the team support take it up forward. 

```
Turn off this advice by setting config variable advice.detachedHead to false

Generating local configuration database from kernel ...Kernel version parse failed!
make: *** [Makefile:45: olddefconfig] Error 1
error: build error: error building at STEP "RUN git clone ...odules_install": error while running runtime: exit status 2
[intel-dgpu-on-premise-build-mode-build-5mc65-undefined.log](https://github.com/intel/intel-technology-enabling-for-openshift/files/11845798/intel-dgpu-on-premise-build-mode-build-5mc65-undefined.log)

```

**Comment by uMartinXu** [comment]
@qbarrand @ybettan could you have a look at this from KMM upstream for OKD support? 
This project only deals with OpenShift, and we have no OKD environment.
Thanks!

**Comment by bthurber** [comment]
Linking in the slack conversation:  https://kubernetes.slack.com/archives/C037RE58RED/p1686313602229529

As noted in the discussion, KMM is not supported on OKD.  It is supported upstream in Kubernetes and downstream in OpenShift.  Expectations should be set for minimal best effort for OKD.  Higher level of support is available upstream in the KMM community and downstream with OpenShift.

**Comment by mregmi** [comment]
The DGPU Driver team may not have the backports of the 915 driver for your version of the kernel (6.0.18-200.fc36.x86_64).
 Please check with the maintainers of this project: https://github.com/intel-gpu/intel-gpu-i915-backports
